### ISSUE TITLE
I am having trouble importing Microsoft.AspNet.Identity.Core 2.2.1

### ISSUE THREAD

**Issue by prasKhanal** [ryanbasnet/roomrental#1]
I am getting following error while creating class Appuser subclass of   Microsoft.AspNetCore.Identity.
I got following error in domain dependency.
"Package 'Microsoft.AspNet.Identity.Core 2.2.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project."
![screenshot](https://user-images.githubusercontent.com/6386246/40263798-fd31d330-5b5a-11e8-8eb1-c59a13352c09.png)

**Comment by ryanbasnet** [comment]
restore the nuget package it should install required packages and should
not have error

**Comment by prasKhanal** [comment]
Same error after I did that.
Package 'Microsoft.AspNet.Identity.Core 2.2.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by prasKhanal** [comment]
How can i change target  NETFramework,Version=v4.6.1 to target framework '.NETStandard,Version=v2.0'.

**Comment by prasKhanal** [comment]
Problem solved:
Microsoft.AspNet.Identity.Core is an old package for ASP.NET 4  not for ASP.NET Core.
We need Microsoft.AspNetCore.Identity package for ASP.NET Core

**Comment by prasKhanal** [comment]
<Reference Include="Microsoft.Extensions.Identity.Stores">
 <HintPath>C:\Users\rajesh\.nuget\packages\microsoft.extensions.identity.stores\2.0.1\lib\netstandard2.0\Microsoft.Extensions.Identity.Stores.dll</HintPath>
    </Reference>
TO

 <Reference Include="Microsoft.Extensions.Identity.Stores">     <HintPath>C:\Users\Newuser\.nuget\packages\microsoft.extensions.identity.stores\2.0.1\lib\netstandard2.0\Microsoft.Extensions.Identity.Stores.dll</HintPath>
    </Reference>

ON

RoomRental.Domain.csproj
